# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/


# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/plugins.conf
# Add any other personal Hyprland configuration below
windowrulev2 = float, class:^(btop-float)$# windowrule = workspace 5, match:class qemu
exec-once = swww-daemon &
exec-once = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-light"
exec-once = swww img "/home/dog/Downloads/macos-tahoe-26-5120x2880-22675.jpg"
exec-once = elephant &
exec-once = waybar &
layerrule = blur, waybar
layerrule = ignorealpha 0, waybar
layerrule = ignorezero, waybar
# This tells Hyprland to blur any window with the class "Alacritty"
windowrulev2 = opacity 0.0 0.0,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
# Make Dolphin (Files) and Pavucontrol (Volume) float by default
# Modern Window Rules v2 for Dolphin and Audio
windowrulev2 = float, class:^(org.kde.dolphin)$
windowrulev2 = size 800 500, class:^(org.kde.dolphin)$
windowrulev2 = center, class:^(org.kde.dolphin)$
# Flexible rule to catch pavucontrol under any class name
windowrulev2 = float, class:^(.*pavucontrol.*)$
windowrulev2 = size 700 450, class:^(.*pavucontrol.*)$
windowrulev2 = center, class:^(.*pavucontrol.*)$
exec-once = hyprpm reload -n
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
# REMOVE the 'opaque' line and add these:
# This makes Alacritty translucent so the blur can show through
# This ensures it stays "floating" in the blur engine
bind = SUPER, M, exit
