plugin {
    dynamic-cursors {
        enabled = true
        mode = stretch # Choices: rotate, tilt, stretch, none
        threshold = 2

        hyprcursor {
            enabled = false
        } 

        # Optional: Shake to find (magnifies cursor when moved fast)
        shake {
            enabled = true
            threshold = 5.0
            magnification = 4.0
            duration = 100000000
        }
    }
}
plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = center current # [center/first] [current/all]
    }
}
plugin {
    hyprbars {
        bar_height = 24
        bar_buttons_alignment = left

        # RED
        hyprbars-button = rgb(ff5f56), 12,   , hyprctl dispatch killactive, rgb(000000)
        
        # YELLOW - Explicitly filling the 5th argument to stop the shift
        hyprbars-button = rgb(ffbd2e), 12,   , hyprctl dispatch killactive, rgb(000000)
        
        # GREEN
        hyprbars-button = rgb(27c93f), 12, , hyprctl dispatch fullscreen 1, rgb(000000)
    }
}
plugin {
    hyprbars {
        bar_text_align = center
        bar_buttons_alignment = left
        # Adjust spacing if needed
        bar_padding = 10
        bar_button_padding = 8
    }
}

plugin:liquid-glass {
    blur_strength = 1.5
    refraction_strength = 0.15
    chromatic_aberration = 0.020
    fresnel_strength = 0.62
    specular_strength = 0.53
}
# Toggle the workspace overview
#bind = SUPER, TAB, hyprexpo:expo, toggle
plugin {
    hyprtrails {
        # Translucent glass white
        color = rgba(ffffff44) 
        
        # Lower history = faster cleanup (no squares)
        history_points = 12
        
        # Smoother, faster bezier for immediate disappearance
        bezier = quartOut, 0.25, 1, 0.5, 1
        
        # How many segments are drawn (keep this low for performance)
        points_per_step = 2
    }
}
plugin {
    hyprfocus {
    enabled = yes
    animate_floating = yes
    animate_workspacechange = yes
    focus_animation = flash
    # Subtle glass-like flash
    flash {
        flash_opacity = 0.5
        in_bezier = reagent
        in_speed = 0.5
        out_bezier = reagent
        out_speed = 3
    }
}
}
# This will toggle the expo overview
bind = SUPER, Tab, hyprexpo:expo, toggle
